/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: hello.h
  Source: /workspace/src/proj/hello.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_HELLO_H_DEA0FA27500D0EB1500348EB33246FD3
#define DDSC_HELLO_H_DEA0FA27500D0EB1500348EB33246FD3

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct demo_Hello
{
  char * msg;
} demo_Hello;

extern const dds_topic_descriptor_t demo_Hello_desc;

#define demo_Hello__alloc() \
((demo_Hello*) dds_alloc (sizeof (demo_Hello)));

#define demo_Hello_free(d,o) \
dds_sample_free ((d), &demo_Hello_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_HELLO_H_DEA0FA27500D0EB1500348EB33246FD3 */
