/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: counter.h
  Source: /workspace/src/proj_cpp/counter.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_COUNTER_H_BDF20CC485DA9977145E836F43E2C913
#define DDSC_COUNTER_H_BDF20CC485DA9977145E836F43E2C913

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct demo_Counter
{
  int32_t value;
} demo_Counter;

extern const dds_topic_descriptor_t demo_Counter_desc;

#define demo_Counter__alloc() \
((demo_Counter*) dds_alloc (sizeof (demo_Counter)));

#define demo_Counter_free(d,o) \
dds_sample_free ((d), &demo_Counter_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_COUNTER_H_BDF20CC485DA9977145E836F43E2C913 */
